### ISSUE TITLE
Allow GluCat to transform between matrix_multi and framed_multi

### ISSUE THREAD

**Issue by penguian** [ga-developers/ga-benchmark#5]
For GluCat to transform between `matrix_multi<>` and `framed_multi<>`, the indices `LO` and `HI` should be approximately equal in absolute value, and should be large enough to allow . For the benchmarks, I would suggest that for both
[source/GluCatFramedMulti/SpecializedAlgebra.hpp](https://github.com/ga-developers/ga-benchmark/blob/master/source/GluCatFramedMulti/SpecializedAlgebra.hpp)
and
[source/GluCatMatrixMulti/SpecializedAlgebra.hpp](https://github.com/ga-developers/ga-benchmark/blob/master/source/GluCatMatrixMulti/SpecializedAlgebra.hpp)
the following definitions should be used.
```
#if (GABENCHMARK_D_DIMENSIONS < 4)
#define GABENCHMARK_GLUCAT_POSITIVE_GENERATORS (4)
#define GABENCHMARK_GLUCAT_NEGATIVE_GENERATORS (-4)
#else
#define GABENCHMARK_GLUCAT_POSITIVE_GENERATORS (8)
#define GABENCHMARK_GLUCAT_NEGATIVE_GENERATORS (-8)
#endif
``` 
This should be enough to accommodate all models to be tested.

For details, see https://github.com/penguian/glucat/blob/master/glucat/framed_multi_imp.h 
https://github.com/penguian/glucat/blob/master/glucat/matrix_multi_imp.h
and https://github.com/penguian/glucat/blob/master/glucat/index_set_imp.h

**Comment by laffernandes** [comment]
The `GABENCHMARK_GLUCAT_POSITIVE_GENERATORS` and `GABENCHMARK_GLUCAT_NEGATIVE_GENERATORS` macros are used in the `MakeVector()` function to convert index values of basis vectors ranging from `0` to `GABENCHMARK_N_DIMENSIONS - 1` to the respective index values used by GluCat (for details, see [GluCatFramedMulti/SpecializedUtils.hpp](https://github.com/ga-developers/ga-benchmark/blob/master/source/GluCatFramedMulti/SpecializedUtils.hpp)). In GluCat, index values range from `framed_multi<...>::index_set_t::v_low` to `-1` and from `1` to `framed_multi<...>::index_set_t::v_hi`, depending on the signature R^{p, q}. For instance, assuming R^{4,1}, vector e(4) in the benchmark must be translated to e(-1) in GluCat.

Therefore, `GABENCHMARK_GLUCAT_POSITIVE_GENERATORS` and `GABENCHMARK_GLUCAT_NEGATIVE_GENERATORS` must be set according to the actual number of basis vectors squaring to positive (p) and negative (q) values in the current model.

Could we use an implementation like this to accommodate all models to be tested?
```c
#if GABENCHMARK_CHECK_MODEL(ConformalModel)

...

#elif GABENCHMARK_CHECK_MODEL(MinkowskiModel)

    #define GABENCHMARK_GLUCAT_NEGATIVE_GENERATORS 1
    #define GABENCHMARK_GLUCAT_POSITIVE_GENERATORS ((GABENCHMARK_D_DIMENSIONS) + 1)

#endif

    using multivector_t = framed_multi<real_t, -GABENCHMARK_N_DIMENSIONS, GABENCHMARK_N_DIMENSIONS>;
```

The `GABENCHMARK_N_DIMENSIONS` macro is defined in [Declarations.hpp](https://github.com/ga-developers/ga-benchmark/blob/master/Declarations.hpp)

This way the number of positive and negative generators set in the specialization of `framed_multi<...>` and `matrix_multi<...>` will be the same, and the MakeVector() will be able to perform the correct translation of indices.

**Comment by penguian** [comment]
I have now created a pull request with code which accomplished what I set out to do.
